<?php
$provinces = $this->getProvinces();
?>
<style>
    ul#left{
        display: inline-block;
        width:30%;
        vertical-align: top;
    }
    ul#right{
        display: inline-block;
        width:50%;
    }
    label{
        width:7%;
        display: block;
    }
</style>
<form action="<?php echo Mage::getUrl('adminstorelocator/adminhtml_index/save') ?>" method="post">
    <fieldset>
        <ul>
            <ul id="left">
                <li>
                    <label for="name">Name</label>
                    <input type="text" id="name" name="name" />
                </li>
                <li>
                    <label for="address">Address</label>
                    <input type="text" id="address" name="address" />
                </li>
                <li>
                    <label for="lat">Latitude</label>
                    <input type="text" id="lat" name="lat" />
                </li>
                <li>
                    <label for="lng">Longitude</label>
                    <input type="text" id="lng" name="lng" />
                </li>
                <li>
                    <label for="telephone">Telephone</label>
                    <input type="text" id="telephone" name="telephone" />
                </li>
                <li>
                    <label for="province">Province</label>
                    <select id="province" name="province">
                        <?php
                        foreach ($provinces as $province){
                            echo "<option value='".$province['id']."'>".$province['storelocator_province']."</option>";
                        }
                        ?>
                    </select>
                </li>
            </ul>
            <ul id="right">
                <li>
                    <label for="mon">Monday</label>
                    <input type="text" id="mon_from" name="mon_from" value="09:00" /> - <input type="text" id="mon_to" name="mon_to" value="18:00" /><br/>
                    <label for="tue">Tuesday</label>
                    <input type="text" id="tue_from" name="tue_from" value="09:00" /> - <input type="text" id="tue_to" name="tue_to" value="18:00" /><br/>
                    <label for="wed">Wednesday</label>
                    <input type="text" id="wed_from" name="wed_from" value="09:00" /> - <input type="text" id="wed_to" name="wed_to" value="18:00" /><br/>
                    <label for="thu">Thursday</label>
                    <input type="text" id="thu_from" name="thu_from" value="09:00" /> - <input type="text" id="thu_to" name="thu_to" value="18:00" /><br/>
                    <label for="fri">Friday</label>
                    <input type="text" id="fri_from" name="fri_from" value="09:00" /> - <input type="text" id="fri_to" name="fri_to" value="18:00" /><br/>
                    <label for="sat">Saturday</label>
                    <input type="text" id="sat_from" name="sat_from" value="09:00" /> - <input type="text" id="sat_to" name="sat_to" value="18:00" /><br/>
                    <label for="sun">Sunday</label>
                    <input type="text" id="sun_from" name="sun_from" value="09:00" /> - <input type="text" id="sun_to" name="sun_to" value="18:00" /><br/>
                </li>

            </ul>
            <li id="left">
                <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"  />
                <input type="submit" value="Add Store" />
            </li>
        </ul>
    </fieldset>
</form>
<?php
echo $this->methodblock();
?>