<?php
$store_id = Mage::registry('store_id');
$provinces = $this->getProvinces();
$store = $this->getStoreData(true ,$store_id);
$store_hours = $this->readStoreHours($store[0]['store_hours']);
?>
<style>
    ul#left{
        display: inline-block;
        width:30%;
        vertical-align: top;
    }
    ul#right{
        display: inline-block;
        width:50%;
    }
    label{
        width:7%;
        display: block;
    }
</style>
<form action="<?php echo Mage::getUrl('adminstorelocator/adminhtml_index/save/edit/'.$store_id) ?>" method="post">
    <fieldset>
        <ul>
            <ul id="left">
                <li>
                    <label for="name">Name</label>
                    <input type="text" id="name" name="name" value="<?=$store[0]['name']?>" />
                </li>
                <li>
                    <label for="address">Address</label>
                    <input type="text" id="address" name="address" value="<?=$store[0]['address']?>"/>
                </li>
                <li>
                    <label for="lat">Latitude</label>
                    <input type="text" id="lat" name="lat" value="<?=$store[0]['lat']?>"/>
                </li>
                <li>
                    <label for="lng">Longitude</label>
                    <input type="text" id="lng" name="lng" value="<?=$store[0]['lng']?>"/>
                </li>
                <li>
                    <label for="telephone">Telephone</label>
                    <input type="text" id="telephone" name="telephone" value="<?=$store[0]['telephone']?>"/>
                </li>
                <li>
                    <label for="province">Province</label>
                    <select id="province" name="province">
                        <?php
                        foreach ($provinces as $province){
                            if($store[0]['storelocator_province_id'] == $province['id']){
                                echo "<option value='".$province['id']."' selected='selected'>".$province['storelocator_province']."</option>";
                            } else {
                                echo "<option value='".$province['id']."'>".$province['storelocator_province']."</option>";
                            }
                        }
                        ?>
                    </select>
                </li>
            </ul>
            <ul id="right">
                <li>
                    <label for="mon">Monday</label>
                    <input type="text" id="mon_from" name="mon_from" value="<?=$store_hours['mon_from']?>" /> - <input type="text" id="mon_to" name="mon_to" value="<?=$store_hours['mon_to']?>" /><br/>
                    <label for="tue">Tuesday</label>
                    <input type="text" id="tue_from" name="tue_from" value="<?=$store_hours['tue_from']?>" /> - <input type="text" id="tue_to" name="tue_to" value="<?=$store_hours['tue_to']?>" /><br/>
                    <label for="wed">Wednesday</label>
                    <input type="text" id="wed_from" name="wed_from" value="<?=$store_hours['wed_from']?>" /> - <input type="text" id="wed_to" name="wed_to" value="<?=$store_hours['wed_to']?>" /><br/>
                    <label for="thu">Thursday</label>
                    <input type="text" id="thu_from" name="thu_from" value="<?=$store_hours['thu_from']?>" /> - <input type="text" id="thu_to" name="thu_to" value="<?=$store_hours['thu_to']?>" /><br/>
                    <label for="fri">Friday</label>
                    <input type="text" id="fri_from" name="fri_from" value="<?=$store_hours['fri_from']?>" /> - <input type="text" id="fri_to" name="fri_to" value="<?=$store_hours['fri_to']?>" /><br/>
                    <label for="sat">Saturday</label>
                    <input type="text" id="sat_from" name="sat_from" value="<?=$store_hours['sat_from']?>" /> - <input type="text" id="sat_to" name="sat_to" value="<?=$store_hours['sat_to']?>" /><br/>
                    <label for="sun">Sunday</label>
                    <input type="text" id="sun_from" name="sun_from" value="<?=$store_hours['sun_from']?>" /> - <input type="text" id="sun_to" name="sun_to" value="<?=$store_hours['sun_to']?>" /><br/>
                </li>

            </ul>
            <li id="left">
                <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"  />
                <input type="submit" value="Edit Store" />
            </li>
        </ul>
    </fieldset>
</form>
<?php
//echo $this->methodblock();
?>