<div id="storelocator-container">
    <h1>Stores</h1>
    <div id="store_filter">
        <label for="province">Province</label>
        <select id="province" name="province">
            <option value="">ALL</option>
            <?php
            $provinces = $this->getProvinces();
            foreach ($provinces as $province){
                echo "<option value='".$province['id']."'>".$province['storelocator_province']."</option>";
            }
            ?>
        </select>
    </div><br/>
    <div id="map_canvas"></div>
    <ul id="marker_list"></ul>
</div>
<?php
$maps_include = '<script async defer src="https://maps.googleapis.com/maps/api/js?key='.Mage::getStoreConfig('storelocator/section_one/google_maps_api_key').'&callback=initMap">';
//echo $this->methodblock(); die();
//echo $this->getJsonStores();
?>

<script>
    function initMap() {
        google.maps.event.addDomListener(window, "load", initialize);
    }

    var storeList = <?= $this->getJsonStores()?>;
    var infoWnd, mapCanvas;

    function initialize() {
        //Creates a map object.
        var mapDiv = document.getElementById("map_canvas");
        mapCanvas = new google.maps.Map(mapDiv);
        mapCanvas.setMapTypeId(google.maps.MapTypeId.ROADMAP);

        //Creates a infowindow object.
        infoWnd = new google.maps.InfoWindow();
        var lat;
        var lng;
        //Mapping markers on the map
        var bounds = new google.maps.LatLngBounds();
        var store, i, latlng;
        document.getElementById("marker_list").innerHTML = "";
        for (i = 0; i <= (storeList.length) -1; i++) {
            //Creates a marker
            store = storeList[i];
            lat = store.lat;
            lng = store.lng;
            //console.log(store);
            latlng = new google.maps.LatLng(lat, lng);
            bounds.extend(latlng);
            var marker = createMarker(
                mapCanvas, latlng, store
            );

            //Creates a sidebar button for the marker
            createMarkerButton(marker);
        }
        //Fits the map bounds
        mapCanvas.fitBounds(bounds);
    }

    function createMarker(map, latlng, store) {
        //Creates a marker
        var marker = new google.maps.Marker({
            position : latlng,
            map : map,
            animation: google.maps.Animation.DROP,
            title : store.name
        });

        var hours = jQuery.parseJSON(store.store_hours);
        //The infoWindow is opened when the sidebar button is clicked
        google.maps.event.addListener(marker, "click", function(){
            infoWnd.setContent('<strong>' + store.name + '</title></strong><br/><br/>'+ store.address +'<br/><br/>' +
                '<strong>Coordinates: </strong>'+ store.lat +', '+ store.lng+
                '<br/><strong>Telephone:</strong>'+store.telephone+
                '<br/><br/><strong>Store Times:</strong><br/>' +
                '<u>Monday:</u> '+hours["Monday"]+'<br/>'+
                '<u>Tuesday:</u> '+hours["Tuesday"]+'<br/>'+
                '<u>Wednesday:</u> '+hours["Wednesday"]+'<br/>'+
                '<u>Thursday:</u> '+hours["Thursday"]+'<br/>'+
                '<u>Friday:</u> '+hours["Friday"]+'<br/>'+
                '<u>Saturday:</u> '+hours["Saturday"]+'<br/>'+
                '<u>Sunday:</u> '+hours["Sunday"]
            );
            infoWnd.open(map, marker);
        });
        return marker;
    }

    function createMarkerButton(marker) {
        //Creates a sidebar button
        var ul = document.getElementById("marker_list");
        var li = document.createElement("li");
        var title = marker.getTitle();
        li.innerHTML = title;
        ul.appendChild(li);

        //Trigger a click event to marker when the button is clicked.
        google.maps.event.addDomListener(li, "click", function(){
            google.maps.event.trigger(marker, "click");
        });
    }

    jQuery('#province').change(function(){
        //alert(jQuery('#province').val());
        var province_id = jQuery('#province').val();
        new Ajax.Request("<?= $this->getUrl('storelocator/index/getJsonStores') ?>", {
            method: 'POST',
            dataType: 'json',
            parameters: {'province_id':province_id},
            onComplete: function(data){
                var stores = data.responseText.evalJSON();
                //alert($.parseJSON(data));
                storeList = stores;
                if(storeList != 'null' || storeList != ''){
                    initialize();
                }
            }
        });
    });
</script>
<?=$maps_include?>
</script>

</script>



